# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
##assignment 1:Array creation and manipulation

import numpy as np
import random

arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)
arr1[:,2] = 1
print(arr1)

[[ 9 12 15  9  6]
 [18 13 17  3  8]
 [ 3 17  2  2 11]
 [16  3 20  7 17]
 [17  5 15 15  2]]
[[ 9 12  1  9  6]
 [18 13  1  3  8]
 [ 3 17  1  2 11]
 [16  3  1  7 17]
 [17  5  1 15  2]]


In [2]:
#shape of (4,4) and replace principal diagnol with 0
arr2 = np.random.randint(1,17,size=(4,4))
print(arr2)
np.fill_diagonal(arr2,0)
print(arr2)


[[ 8  7  8 16]
 [ 4 12  3 14]
 [ 4  4 12 14]
 [10  6  4 10]]
[[ 0  7  8 16]
 [ 4  0  3 14]
 [ 4  4  0 14]
 [10  6  4  0]]


In [3]:
#assignment 2 Array indexing and slicing

#Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr3 = np.random.randint(1,37,size = (6,6))
print(arr3)
arr3[2:5,1:4]



[[14 26 16 24 36 36]
 [ 5 18  9 21 14 35]
 [15 28 18 26  7  8]
 [11 36 26  4 35  6]
 [15  5  9  6 25  9]
 [ 2 14 23 15  8 15]]


array([[28, 18, 26],
       [36, 26,  4],
       [ 5,  9,  6]])

In [4]:
##2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr4 = np.random.randint(1,21,size=(5,5))
print(arr4)
border_elements = np.concatenate((arr4[0,:],arr4[-1,:],arr4[1:-1,0],arr4[1:-1,-1]))
print(border_elements)

[[18  9  7  5  8]
 [15  9 19 14  1]
 [ 7 19 17 10  6]
 [15 20 15  1  1]
 [ 8  8 14 13  6]]
[18  9  7  5  8  8  8 14 13  6 15  7 15  1  6  1]


In [5]:
#Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr5 = np.random.randint(1,21,size=(3,4))
print(arr5)
arr6 = np.random.randint(21,41,size=(3,4))
print(arr6)
#addition 
arr7 = arr5 + arr6
print(arr7)
#subtraction
arr8 = arr5 - arr6
print(arr8)
#multiplication
arr9 = arr5 * arr6
print(arr9)
#division
arr10 = arr5 /arr6
print(arr10)


[[13 13  9  8]
 [19 17 10  1]
 [ 3  7 17 20]]
[[27 30 37 24]
 [36 23 34 24]
 [24 21 25 40]]
[[40 43 46 32]
 [55 40 44 25]
 [27 28 42 60]]
[[-14 -17 -28 -16]
 [-17  -6 -24 -23]
 [-21 -14  -8 -20]]
[[351 390 333 192]
 [684 391 340  24]
 [ 72 147 425 800]]
[[0.48148148 0.43333333 0.24324324 0.33333333]
 [0.52777778 0.73913043 0.29411765 0.04166667]
 [0.125      0.33333333 0.68       0.5       ]]


In [6]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr11 = np.random.randint(1,17,size=(4,4))
print(arr11)
row_sum = np.sum(arr11,axis=1)
col_sum = np.sum(arr11,axis=0)
print("row_sum")
print(row_sum)
print("col_num")
print(col_sum)

[[ 9 11 15 10]
 [12  2 11 16]
 [ 3 16  9  4]
 [ 5  7  1  1]]
row_sum
[45 41 32 14]
col_num
[29 36 36 31]


In [7]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr12 = np.random.randint(1,21,size=(5,5))
print(arr12)
#mean
mean = np.mean(arr12)
print("mean")
print(mean)
#median
median=np.median(arr12)
print("median")
print(median)
#standard deviation
std=np.std(arr12)
print("standard deviation")
print(std)
#variance
var = np.var(arr12)
print("variance")
print(var)


[[ 4 11 18 20 10]
 [12  1 18  4  7]
 [11 17 17 20 11]
 [11  7  5 11  9]
 [17 20 13  8  7]]
mean
11.56
median
11.0
standard deviation
5.448522735567871
variance
29.6864


In [8]:
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr13 = np.random.randint(1,10,size=(3,3))
print(arr13)
mean = np.mean(arr13)
std = np.std(arr13)
normalised_array = (arr13 - mean)/std
print(normalised_array)


[[5 7 6]
 [6 4 1]
 [8 9 9]]
[[-0.45834925  0.3666794  -0.04583492]
 [-0.04583492 -0.87086357 -2.10840654]
 [ 0.77919372  1.19170805  1.19170805]]


In [9]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers.
#  Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr14= np.random.randint(1,21,size=(3,3))
print(arr14)
oned_array = np.random.randint(1,21,size=(3,))
print(oned_array)
result = arr14 + oned_array
print(result)


[[15  7  6]
 [20 13  2]
 [ 2  9 11]]
[12  9 19]
[[27 16 25]
 [32 22 21]
 [14 18 30]]


In [10]:
#2. Create a NumPy array of shape (4, 4) filled with random integers.
#  Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr15 = np.random.randint(1,16,size=(4,4))
print(arr15)
print("1d array")
onedim = np.random.randint(1,21,size=(4,))
print(onedim)
result =  arr15 - onedim[:,np.newaxis]
print("result")
print(result)

[[ 9 14 12 15]
 [ 5  7 14 10]
 [10  4  2  4]
 [ 2  8  7  5]]
1d array
[20 14 17 18]
result
[[-11  -6  -8  -5]
 [ -9  -7   0  -4]
 [ -7 -13 -15 -13]
 [-16 -10 -11 -13]]


In [11]:
# Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
arr16 = np.random.randint(1,10,size=(3,3))
print(arr16)
print("determinant")
print(np.linalg.det(arr16))
print("inverse")
print(np.linalg.inv(arr16))
print("eigenvalues")
print(np.linalg.eigvals(arr16))

[[3 7 2]
 [9 7 6]
 [1 3 1]]
determinant
-14.000000000000009
inverse
[[ 0.78571429  0.07142857 -2.        ]
 [ 0.21428571 -0.07142857  0.        ]
 [-1.42857143  0.14285714  3.        ]]
eigenvalues
[14.51584921 -3.77156855  0.25571934]


In [14]:
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

arr17 = np.random.randint(1,11,size=(2,3))
print("first array")
print(arr17)
arr18 = np.random.randint(1,11,size=(3,2))
print("second array")
print(arr18)
print("mutiplication of the arrays by dot")
print(np.dot(arr17,arr18))



first array
[[9 6 2]
 [1 2 5]]
second array
[[10  5]
 [10  8]
 [ 5  9]]
mutiplication of the arrays by dot
[[160 111]
 [ 55  66]]


In [18]:
# Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Reshape the array to shape (1, 9) and then to shape (9, 1).

arr19 = np.random.randint(1,10,size = (3,3))
print("original array")
print(arr19)
print("reshaped size to (1,9)")
print(arr19.reshape((1,9)))
print("reshaped to size (9,1)")
print(arr19.reshape((9,1)))

original array
[[3 5 1]
 [8 6 8]
 [1 9 3]]
reshaped size to (1,9)
[[3 5 1 8 6 8 1 9 3]]
reshaped to size (9,1)
[[3]
 [5]
 [1]
 [8]
 [6]
 [8]
 [1]
 [9]
 [3]]


In [19]:
#2. Create a NumPy array of shape (5, 5) filled with random integers. 
# Flatten the array and then reshape it back to (5, 5).

arr20 = np.random.randint(1,21,size = (5,5))
print("original array")
print(arr20)
print("flattened array")
flattened_array = arr20.flatten()
print(flattened_array)
print("reshaping to (5,5)")
print(flattened_array.reshape(5,5))

original array
[[ 6 20  3 10 12]
 [18 10 17 13 16]
 [20  5  3 16  2]
 [17 18  4 11  4]
 [11  1  4 11  6]]
flattened array
[ 6 20  3 10 12 18 10 17 13 16 20  5  3 16  2 17 18  4 11  4 11  1  4 11
  6]
reshaping to (5,5)
[[ 6 20  3 10 12]
 [18 10 17 13 16]
 [20  5  3 16  2]
 [17 18  4 11  4]
 [11  1  4 11  6]]


In [21]:
# Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers.
#  Use fancy indexing to extract the elements at the corners of the array.

arr21 = np.random.randint(1,21,size=(5,5))
print("original array")
print(arr21)
print("extracting the corner elements")
print(arr21[[0,0,-1,-1],[0,-1,0,-1]]) #(0,0),(0,-1),(-1,0),(-1,-1)

original array
[[ 4  2 10  5 16]
 [ 4  9  9  2  5]
 [17 13  8  3 20]
 [ 2  7 17  6 13]
 [19 15  8  2 14]]
extracting the corner elements
[ 4 16 19 14]


In [22]:
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

arr22 = np.random.randint(1,17,size=(4,4))
print("original array")
print(arr22)
arr22[arr22 > 10] = 10
print("modified array")
print(arr22)

original array
[[ 9  1 16  4]
 [ 2 12 13  1]
 [12 15 11  4]
 [ 7  2 14 11]]
modified array
[[ 9  1 10  4]
 [ 2 10 10  1]
 [10 10 10  4]
 [ 7  2 10 10]]


In [23]:
# Assignment 9: Structured Arrays

#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). 
# Add some data and sort the array by age.

data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice',15,65.5),('bob',13,54.3),('charlie',34,43.6)],dtype=data_type)
print("original array")
print(data)

#sort the data by age
sorted_data = np.sort(data,order='age')
print("sorted by age")
print(sorted_data)

original array
[('Alice', 15, 65.5) ('bob', 13, 54.3) ('charlie', 34, 43.6)]
sorted by age
[('bob', 13, 54.3) ('Alice', 15, 65.5) ('charlie', 34, 43.6)]


In [24]:
#2. Create a structured array with fields 'x' and 'y' (both integers).
#  Add some data and compute the Euclidean distance between each pair of points.
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)],dtype = data_type)
print("original array")
print(data)
distances = np.sqrt((data['x'][:,np.newaxis] - data['x'])**2 + (data['y'][:,np.newaxis] - data['y'])**2)
print("euclidean distances")
print(distances)

original array
[(1, 2) (3, 4) (5, 6)]
euclidean distances
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [25]:
## Assignment 10: Masked Arrays

#1. Create a masked array of shape (4, 4) with random integers and
#  mask the elements greater than 10. Compute the sum of the unmasked elements.

import numpy.ma as ma

arr23 = np.random.randint(1,17,size = (4,4))
print("original array")
print(arr23)

masked_array = ma.masked_greater(arr23,10)
print("masked array")
print(masked_array)

sum_masked_elements = masked_array.sum()
print("sum")
print(sum_masked_elements)

original array
[[12 14  8  3]
 [ 5  6 11 15]
 [14 10  6 11]
 [11  8  7  5]]
masked array
[[-- -- 8 3]
 [5 6 -- --]
 [-- 10 6 --]
 [-- 8 7 5]]
sum
58


In [28]:
#2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements.
#  Replace the masked elements with the mean of the unmasked elements.

arr24 = np.random.randint(1,10,size =(3,3))
print("original array")
print(arr24)
mas_array =ma.masked_array(arr24,mask = np.eye(3,dtype=bool))
print("masked array")
print(mas_array)

mean_of = arr24.mean()
print("mean: ",mean_of)
replaced_array = mas_array.filled(mean_of)
print("replacing array with the mean")
print(replaced_array)

original array
[[2 8 4]
 [8 9 6]
 [7 6 5]]
masked array
[[-- 8 4]
 [8 -- 6]
 [7 6 --]]
mean:  6.111111111111111
replacing array with the mean
[[6 8 4]
 [8 6 6]
 [7 6 6]]
