# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
##assignment 1:Array creation and manipulation

import numpy as np
import random

arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)
arr1[:,2] = 1
print(arr1)

[[12 20  8  5 19]
 [ 8  2 14  2  6]
 [16  8 20  3  9]
 [11 16 18 20 17]
 [ 6  2 12 11 12]]
[[12 20  1  5 19]
 [ 8  2  1  2  6]
 [16  8  1  3  9]
 [11 16  1 20 17]
 [ 6  2  1 11 12]]


In [2]:
#shape of (4,4) and replace principal diagnol with 0
arr2 = np.random.randint(1,17,size=(4,4))
print(arr2)
np.fill_diagonal(arr2,0)
print(arr2)


[[ 5  4  8 10]
 [14 16 13 16]
 [16 16  1 10]
 [15 13 16 12]]
[[ 0  4  8 10]
 [14  0 13 16]
 [16 16  0 10]
 [15 13 16  0]]


In [3]:
#assignment 2 Array indexing and slicing

#Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

arr3 = np.random.randint(1,37,size = (6,6))
print(arr3)
arr3[2:5,1:4]



[[ 7 29 28  6  8  8]
 [20  8 29  9 28  9]
 [31 30 30 11  6  2]
 [20 21 20 36 27 21]
 [29 27 33 33 28 20]
 [ 9 22 14 21 14  7]]


array([[30, 30, 11],
       [21, 20, 36],
       [27, 33, 33]])

In [6]:
##2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr4 = np.random.randint(1,21,size=(5,5))
print(arr4)
border_elements = np.concatenate((arr4[0,:],arr4[-1,:],arr4[1:-1,0],arr4[1:-1,-1]))
print(border_elements)

[[13  4  2 20 20]
 [ 7 11  2  4  8]
 [ 1 18  1  8  4]
 [ 1 19 11 11 17]
 [ 2  9  1 10  1]]
[13  4  2 20 20  2  9  1 10  1  7  1  1  8  4 17]


In [8]:
#Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

arr5 = np.random.randint(1,21,size=(3,4))
print(arr5)
arr6 = np.random.randint(21,41,size=(3,4))
print(arr6)
#addition 
arr7 = arr5 + arr6
print(arr7)
#subtraction
arr8 = arr5 - arr6
print(arr8)
#multiplication
arr9 = arr5 * arr6
print(arr9)
#division
arr10 = arr5 /arr6
print(arr10)


[[12  2 14 15]
 [ 7  7 12 17]
 [ 6 16 10  5]]
[[24 25 39 26]
 [34 22 30 39]
 [24 30 28 40]]
[[36 27 53 41]
 [41 29 42 56]
 [30 46 38 45]]
[[-12 -23 -25 -11]
 [-27 -15 -18 -22]
 [-18 -14 -18 -35]]
[[288  50 546 390]
 [238 154 360 663]
 [144 480 280 200]]
[[0.5        0.08       0.35897436 0.57692308]
 [0.20588235 0.31818182 0.4        0.43589744]
 [0.25       0.53333333 0.35714286 0.125     ]]


In [10]:
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr11 = np.random.randint(1,17,size=(4,4))
print(arr11)
row_sum = np.sum(arr11,axis=1)
col_sum = np.sum(arr11,axis=0)
print("row_sum")
print(row_sum)
print("col_num")
print(col_sum)

[[ 8 10 10  5]
 [ 7  1  6  7]
 [ 3  9 12  6]
 [13  7  8  2]]
row_sum
[33 21 30 30]
col_num
[31 27 36 20]


In [12]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr12 = np.random.randint(1,21,size=(5,5))
print(arr12)
#mean
mean = np.mean(arr12)
print("mean")
print(mean)
#median
median=np.median(arr12)
print("median")
print(median)
#standard deviation
std=np.std(arr12)
print("standard deviation")
print(std)
#variance
var = np.var(arr12)
print("variance")
print(var)


[[ 2 15  7 17  8]
 [ 1  7 17  1 13]
 [18  1 15  8 15]
 [10 12  7 20 13]
 [20  6 19  9 14]]
mean
11.0
median
12.0
standard deviation
5.966573556070519
variance
35.6


In [14]:
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9.
#  Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr13 = np.random.randint(1,10,size=(3,3))
print(arr13)
mean = np.mean(arr13)
std = np.std(arr13)
normalised_array = (arr13 - mean)/std
print(normalised_array)


[[9 7 1]
 [7 6 2]
 [2 9 7]]
[[ 1.1835855   0.49634231 -1.56538727]
 [ 0.49634231  0.15272071 -1.22176568]
 [-1.22176568  1.1835855   0.49634231]]


In [16]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers.
#  Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

arr14= np.random.randint(1,21,size=(3,3))
print(arr14)
oned_array = np.random.randint(1,21,size=(3,))
print(oned_array)
result = arr14 + oned_array
print(result)


[[12  6  2]
 [19 12 18]
 [14  1 15]]
[ 5 11 18]
[[17 17 20]
 [24 23 36]
 [19 12 33]]


In [17]:
#2. Create a NumPy array of shape (4, 4) filled with random integers.
#  Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

arr15 = np.random.randint(1,16,size=(4,4))
print(arr15)
print("1d array")
onedim = np.random.randint(1,21,size=(4,))
print(onedim)
result =  arr15 - onedim[:,np.newaxis]
print("result")
print(result)

[[ 7  6  1  9]
 [ 6  3 14  7]
 [12  8  9  7]
 [ 7  2  5 11]]
1d array
[16 18 17  5]
result
[[ -9 -10 -15  -7]
 [-12 -15  -4 -11]
 [ -5  -9  -8 -10]
 [  2  -3   0   6]]
