Numpy


numpy is mainly centered around n-dimensional array object
it also contains linear algebra,fourier transform,random number functions

In [1]:
#importing the numpy
import numpy as np

In [2]:
#np.zeros - creates an array containing number of zeroes
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros((3,4))
#takes tuple as number of rows and columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In numpy, dimension = axis

number of axes = rank (eg : 3*4 matrix is a 2d array of rank 2,the length of 1st axis=3 and 2nd = 4)

list of axis is called shape.like (3,4).rank = shape's length

size of array = total number of elements = product of axis length 

size of array = 12 = 3*4 =12


In [5]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a.shape #this is not a function

(3, 4)

In [11]:
a.ndim  # = len(a.shape)

2

In [12]:
a.size

12

**N- dimensional arrays**

we can crreate n-dimensional arrays with arbitrary rank

In [13]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

numpy arrays are type of **ndarray**

In [15]:
type(np.zeros((2,3)))

numpy.ndarray

np.ones -creates array with all ones

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**np.full**

creates the array with full of given values with given shape

In [17]:
np.full((3,4),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

**np.empty**

it is uninitialised with whatever memory has at that point with the given shape

In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**np.array**

initialise an array using python array

In [20]:
np.array([[1,2,3,4],[10,202,30,40]])

array([[  1,   2,   3,   4],
       [ 10, 202,  30,  40]])

**np.arange**

create an ndarray with given range

In [24]:
print(np.arange(1,5))
print(np.arange(1.0,5.0))
print(np.arange(1,5,0.5))

[1 2 3 4]
[1. 2. 3. 4.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [27]:
#we cant always set up floats because elements in array is not predictable
print(np.arange(0,5/3,1/3))
print(np.arange(0,5/3,0.3333333))
print(np.arange(0,5/3,0.3333334)) #just by increasing one digit,the elements are lesser

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.        0.3333333 0.6666666 0.9999999 1.3333332 1.6666665]
[0.        0.3333334 0.6666668 1.0000002 1.3333336]


**np.linspace**

for the above problem when using floats,we use linspace function  which returns a array with specific number of points evenly distributed between two values

In [28]:
np.linspace(0,5/3,6)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])